python finetune.py \
    --data_root segment-anything/DATA/TN-SCUI2020/segmentation/augtrain \
    --model_type vit_h \
    --checkpoint_path segment-anything/output/sam_vit_h_4b8939.pth \
    --freeze_image_encoder \
    --batch_size 4 \
    --image_size 1024 \
    --steps 1500 \
    --learning_rate 1.e-5 \
    --weight_decay 0.01 \
    --output_dir segment-anything/output/sam_vit_h